# -*- coding: utf-8 -*-
"""PseudoCodigoCavalo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVLHEbn3aImgJGd4fNTG92tVaRWDf3K8
"""

int movimentos = 0;
bool flag = false;

a partir do ponto inicial:

  if(inicial == final):
          flag = true;

  colocar o ponto inicial em uma lista;

  enquanto(flag == false):

    movimentos ++;

    para cada elemento da lista:

      para cada ponto alcançado a partir desse elemento:
        
        
        x +=  y +=
        p1  +1,  +2
        p2  +2,  +1
        p3  +1,  -2
        p4  +2,  -1
        p5  -1,  +2
        p6  -2,  + 1
        p7  -1,  -2
        p8  -2,  -1

  sendo que x e y devem ser >= 0 e <=8, caso contrario, desconsiderar o ponto

        if(ponto alcançado = ponto final):
          flag = true;

        else:
          if(ponto nao existe na lista) acrescentar ponto na lista;
           

  
  print(movimentos);