# -*- coding: utf-8 -*-
"""MainURI1322.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dzPQINpXTYzEdpVECb8kwfKpkTB7Xk0r
"""



import networkx as nx

nodes, edges = map(int, input().split())

if (edges == 0):
  print("Y")  #end if


while (nodes!=0 and edges !=0):
  G = nx.Graph() 
  eul = 0
  neighbors = 0
  

  for x in range(nodes):
     G.add_node(x+1) #end for
     

  for y in range(edges):
     neighbors = input().split() 
     G.add_edge(int(neighbors[0]),int(neighbors[1]))  #end for
    
  
   
  for z in range(nodes):
     eul = G.degree[z+1]
       
          
  if(eul == 0):
     print("N") #end if 
     
  elif((eul % 2) == 0):
     print("Y")  #end if

  elif((eul % 2) != 0):
     print("N") #end if

  nodes, edges = map(int, input().split()) #end while    
    
# A ideia é testar  se o grafo é um circuito
# O teste sera feito atravez de teste com o graus dos vertices
# O codigo funcionará para os casos testes do enunciado